services:
  - type: web
    name: pdf-shala-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: SERVER_API
        value: https://pdf-shala-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 